### ISSUE TITLE
Sound not stopping on mute button pressed

### ISSUE THREAD

**Issue by jcalixte** [cassidoo/typing-game#3]
I think I know what's going on for the sound not paused when pressing the volume button.

You're using the hook `useGameReducer` in two components: `Game.js` and `MuteButton.js` so you're instanciating the `useBattleSound` twice that are completely independent. That's why the `stopBattleSound` in `MuteButton` is not very effective (haha) for the `battleSound` in `Game.js`.

I better understand it when I try to remove the `useGameReducer` function and copy paste the code in components directly, this way I clearly see that they are different variables.

Hope it helps!

Stay awesome

**Comment by cassidoo** [comment]
Ah that is totally why it's not working, thank you for making the issue!
